/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpressorasStatusRouteImport } from './routes/impressoras/status'
import { Route as ImpressorasPapelRouteImport } from './routes/impressoras/papel'
import { Route as ImpressorasMaquinasRouteImport } from './routes/impressoras/maquinas'
import { Route as ImpressorasDashboardRouteImport } from './routes/impressoras/dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasStatusRoute = ImpressorasStatusRouteImport.update({
  id: '/impressoras/status',
  path: '/impressoras/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasPapelRoute = ImpressorasPapelRouteImport.update({
  id: '/impressoras/papel',
  path: '/impressoras/papel',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasMaquinasRoute = ImpressorasMaquinasRouteImport.update({
  id: '/impressoras/maquinas',
  path: '/impressoras/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasDashboardRoute = ImpressorasDashboardRouteImport.update({
  id: '/impressoras/dashboard',
  path: '/impressoras/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/impressoras/dashboard': typeof ImpressorasDashboardRoute
  '/impressoras/maquinas': typeof ImpressorasMaquinasRoute
  '/impressoras/papel': typeof ImpressorasPapelRoute
  '/impressoras/status': typeof ImpressorasStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/impressoras/dashboard': typeof ImpressorasDashboardRoute
  '/impressoras/maquinas': typeof ImpressorasMaquinasRoute
  '/impressoras/papel': typeof ImpressorasPapelRoute
  '/impressoras/status': typeof ImpressorasStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/impressoras/dashboard': typeof ImpressorasDashboardRoute
  '/impressoras/maquinas': typeof ImpressorasMaquinasRoute
  '/impressoras/papel': typeof ImpressorasPapelRoute
  '/impressoras/status': typeof ImpressorasStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inicio'
    | '/login'
    | '/sitemap.xml'
    | '/impressoras/dashboard'
    | '/impressoras/maquinas'
    | '/impressoras/papel'
    | '/impressoras/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/login'
    | '/sitemap.xml'
    | '/impressoras/dashboard'
    | '/impressoras/maquinas'
    | '/impressoras/papel'
    | '/impressoras/status'
  id:
    | '__root__'
    | '/'
    | '/inicio'
    | '/login'
    | '/sitemap.xml'
    | '/impressoras/dashboard'
    | '/impressoras/maquinas'
    | '/impressoras/papel'
    | '/impressoras/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ImpressorasDashboardRoute: typeof ImpressorasDashboardRoute
  ImpressorasMaquinasRoute: typeof ImpressorasMaquinasRoute
  ImpressorasPapelRoute: typeof ImpressorasPapelRoute
  ImpressorasStatusRoute: typeof ImpressorasStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras/status': {
      id: '/impressoras/status'
      path: '/impressoras/status'
      fullPath: '/impressoras/status'
      preLoaderRoute: typeof ImpressorasStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras/papel': {
      id: '/impressoras/papel'
      path: '/impressoras/papel'
      fullPath: '/impressoras/papel'
      preLoaderRoute: typeof ImpressorasPapelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras/maquinas': {
      id: '/impressoras/maquinas'
      path: '/impressoras/maquinas'
      fullPath: '/impressoras/maquinas'
      preLoaderRoute: typeof ImpressorasMaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras/dashboard': {
      id: '/impressoras/dashboard'
      path: '/impressoras/dashboard'
      fullPath: '/impressoras/dashboard'
      preLoaderRoute: typeof ImpressorasDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ImpressorasDashboardRoute: ImpressorasDashboardRoute,
  ImpressorasMaquinasRoute: ImpressorasMaquinasRoute,
  ImpressorasPapelRoute: ImpressorasPapelRoute,
  ImpressorasStatusRoute: ImpressorasStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
